name: .NET CI with Render Deploy + Doxygen PDF

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: WsCrud

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        working-directory: WsCrud
        run: dotnet restore WsCrud.sln

      - name: Build
        working-directory: WsCrud
        run: dotnet build WsCrud.sln --no-restore --configuration Release

      - name: Run tests with Basic Auth secrets
        working-directory: WsCrud
        env:
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
        run: dotnet test WsCrud.Tests/WsCrud.Tests.csproj --no-build --configuration Release --verbosity normal

  docs:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and LaTeX (with Ghostscript)
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen make ghostscript \
            texlive-latex-base texlive-fonts-recommended \
            texlive-latex-recommended texlive-latex-extra

      - name: Generate LaTeX with Doxygen
        run: doxygen Doxyfile

      - name: Build PDF from LaTeX
        working-directory: docs/latex
        run: make

      - name: Upload PDF for reuse
        uses: actions/upload-artifact@v4
        with:
          name: index-pdf
          path: docs/latex/refman.pdf

      - name: Switch to gh-pages branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git switch gh-pages || git checkout --orphan gh-pages
          rm -rf *

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: index-pdf
          path: .

      - name: Rename and commit PDF
        run: |
          mv refman.pdf index.pdf
          git add index.pdf
          git commit -m "Update Doxygen PDF"
          git push origin gh-pages --force

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}